# 歐鴻君 u022451 期中  Feature selection

http://scikit-learn.org/stable/modules/feature_selection.html#feature-selection

In [1]:
from numpy import genfromtxt, zeros
# read the first 4 columns
data = genfromtxt('iris.csv',delimiter=',',usecols=(0,1,2,3))
# read the fifth column
target = genfromtxt('iris.csv',delimiter=',',usecols=(4),dtype=str)
print data.shape
print target.shape
print set (target)

(150, 4)
(150,)
set(['setosa', 'versicolor', 'virginica'])


In [2]:
from sklearn.svm import LinearSVC
from sklearn.feature_selection import SelectFromModel
X, y = data, target
lsvc = LinearSVC(C=0.01, penalty="l1", dual=False).fit(X, y)
model = SelectFromModel(lsvc, prefit=True)
X_new = model.transform(X)
X_new.shape

(150, 3)

In [3]:
t = zeros(len(target))
t[target == 'setosa'] = 1
t[target == 'versicolor'] = 2
t[target == 'virginica'] = 3

In [4]:
SF = LinearSVC()
SF.fit(X_new,t) # training on the iris dataset

LinearSVC(C=1.0, class_weight=None, dual=True, fit_intercept=True,
     intercept_scaling=1, loss='squared_hinge', max_iter=1000,
     multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
     verbose=0)

In [5]:
print SF.predict(X_new[0])

[ 1.]


/opt/conda/envs/python2/lib/python2.7/site-packages/sklearn/utils/validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


In [6]:
print t[0]

1.0


In [7]:
from sklearn import cross_validation
train, test, t_train, t_test = cross_validation.train_test_split(X_new, t
, test_size=0.4, random_state=0)

In [8]:
SF.fit(train,t_train) 
print SF.score(test,t_test)

0.883333333333


In [9]:
from sklearn.metrics import confusion_matrix
print confusion_matrix(SF.predict(test),t_test)

[[16  0  0]
 [ 0 19  3]
 [ 0  4 18]]


In [10]:
from sklearn.metrics import classification_report
print classification_report(SF.predict(test), t_test,
target_names=['setosa', 'versicolor', 'virginica'])

             precision    recall  f1-score   support

     setosa       1.00      1.00      1.00        16
 versicolor       0.83      0.86      0.84        22
  virginica       0.86      0.82      0.84        22

avg / total       0.88      0.88      0.88        60

