# 歐鴻君 u022451 期中  Feature selection

http://scikit-learn.org/stable/modules/feature_selection.html#feature-selection

In [1]:
from numpy import genfromtxt, zeros
# read the first 4 columns
data = genfromtxt('iris.csv',delimiter=',',usecols=(0,1,2,3))
# read the fifth column
target = genfromtxt('iris.csv',delimiter=',',usecols=(4),dtype=str)
print data.shape
print target.shape
print set (target)
X, y = data, target
X.shape

(150, 4)
(150,)
set(['setosa', 'versicolor', 'virginica'])


(150, 4)

In [2]:
from sklearn.svm import LinearSVC
from sklearn.feature_selection import SelectFromModel
lsvc = LinearSVC(C=0.01, penalty="l1", dual=False).fit(X, y)
model = SelectFromModel(lsvc, prefit=True)
X_new = model.transform(X)
X_new.shape

(150, 3)

In [3]:
t = zeros(len(target))
t[target == 'setosa'] = 1
t[target == 'versicolor'] = 2
t[target == 'virginica'] = 3

In [4]:
from sklearn.ensemble import ExtraTreesClassifier
SF = ExtraTreesClassifier()
SF.fit(data,t) # training on the iris dataset

ExtraTreesClassifier(bootstrap=False, class_weight=None, criterion='gini',
           max_depth=None, max_features='auto', max_leaf_nodes=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
           oob_score=False, random_state=None, verbose=0, warm_start=False)

In [5]:
SF.score(data,t)

1.0

In [6]:
from sklearn import cross_validation
train, test, t_train, t_test = cross_validation.train_test_split(data, t
, test_size=0.4, random_state=0)

In [7]:
SF.fit(train,t_train) 
print SF.score(test,t_test)

0.916666666667


In [8]:
from sklearn.metrics import confusion_matrix
print confusion_matrix(SF.predict(test),t_test)

[[16  0  0]
 [ 0 22  4]
 [ 0  1 17]]


In [9]:
from sklearn.metrics import classification_report
print classification_report(SF.predict(test), t_test,
target_names=['setosa', 'versicolor', 'virginica'])

             precision    recall  f1-score   support

     setosa       1.00      1.00      1.00        16
 versicolor       0.96      0.85      0.90        26
  virginica       0.81      0.94      0.87        18

avg / total       0.92      0.92      0.92        60

